FROM mcr.microsoft.comdotnetsdk8.0 AS build
WORKDIR src
COPY .csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o apppublish

FROM mcr.microsoft.comdotnetaspnet8.0 AS final
WORKDIR app
COPY --from=build apppublish .
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT [dotnet, ProyectoUnisinu.dll]